name: hijri_calendar
description: "A Dart library for Islamic dates. Explore the Hijri calendar with ease. Perfect for integrating Islamic date functionalities into your applications."
version: 1.0.4+4
repository: https://github.com/Shreemanarjun/hijri_calendar
homepage: https://github.com/Shreemanarjun/hijri_calendar
documentation: https://github.com/Shreemanarjun/hijri_calendar/wiki

topics:
  - calendar
  - hijri
  - date
  - islamic-calendar
  - time

issue_tracker: https://github.com/Shreemanarjun/hijri_calendar/issues


environment:
  sdk: ^3.5.4

# Add regular dependencies here.
# dependencies:
#   # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
